# Don't use language: python; this gives us an unnecessary virtualenv
language: c
# Seems to be needed to prevent hanging in Python 2.7
# https://github.com/travis-ci/travis-ci/issues/6861
sudo: required

env:
  # Build and test package on all supported python version
  - BUILD_TARGET=3.7
  - BUILD_TARGET=3.6 
  - BUILD_TARGET=2.7
  # Smoketest package on conda canary
  - BUILD_TARGET=3.7 CONDA_CANARY="-c conda-canary"

os:
  - linux
  - osx

matrix:
  # conda canary shouldn't block the build, just show us an FYI
  allow_failures:
    - env: BUILD_TARGET=3.7 CONDA_CANARY="-c conda-canary"

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
  - conda install -q $CONDA_CANARY -c defaults -c conda-forge conda conda-build conda-verify codecov flake8 pep257 yapf
  - conda info -a
  - export LANG=en_US.UTF-8
  - export COVERAGE_DIR=":$HOME/htmlcov"
  - printenv | sort

script:
  - conda build conda.recipe --python=$BUILD_TARGET
  - conda activate
  - python scripts/run_tests.py --format-only

after_success:
  - codecov
