# Build only the master branch, tagged commits, and pull requests
branches:
  only:
    - master

# Don't run the (redundant) branch build with a pull request
skip_branch_with_pr: true

matrix:
  fast_finish: true

environment:
  PYTHONUNBUFFERED: 1
  COVERAGE_DIR: ""
  MINICONDA: C:\\Miniconda3-x64
  matrix:
    - PYTHON_VERSION: 3.7
    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 2.7

install:
  # conda 4.5.11 seems to expect that this directory exists already
  - call %MINICONDA%\Scripts\activate.bat
  # The safety checks are simply intended to ensure that there is enough disk space
  # and the user has the necessary permissions to make environment changes. In a CI
  # environment these are not necessary and slow things down noticeably on Windows.
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda no --set safety_checks disabled
  - conda install -q conda=4.6 conda-build=3.18.10 conda-verify
  - conda info -a

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - conda build conda.recipe --python=%PYTHON_VERSION%
