# Use `conda env create environment.yml` to create a dev environment
name: anaconda-project-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - redis
  - notebook
  - ruamel_yaml
  - anaconda-client
  - requests
  - psutil
  - tornado>=4.2
  - pip
  - keyring
  - pytest
  - pytest-cov
  - coverage
  # Pinned to ensure consistency between local and CI
  - yapf==0.30.0
  - flake8
  - pep257
  # Optional; for multiprocessing tests
  - pytest-xdist
